---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: {{ template "name" . }}
  labels:
    app: website
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      containers:
        - name: website
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.port }}