apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: website-service
  namespace: {{ template "name" . }}
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: website-service
            servicePort: {{ .Values.port }}
          path: /
