---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: {{ template "name" . }}
  labels:
    app: website-app
spec:
  selector:
    app: website-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
